version: '0.7'
package:
  name: 'tng-smp-ns2-k8s-mdc-eids'
  vendor: 'eu.5gtango'
  version: '0.7'
  maintainer: sm-pilot@5gtango.eu
  description: Smart Manufacturing pilot - containerized Machine Data Collector (MDC) with enhanced-IDS (SELK)
descriptor_extension: yml
files:
- path: nsd/mdc-selk.yml
  type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango
- path: vnfd/msf.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: vnfd/lhc.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: vnfd/e.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: vnfd/k.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
