# Dockerfile to build a Suricata docker container

# Credits to: https://github.com/julienyvenat/docker-suricata/blob/master/Dockerfile/Dockerfile

# Set the latest Ubuntu image
FROM centos:7

# File Author
MAINTAINER sm-pilot@5gtango.eu

# Update the repos and install tools
RUN yum update -y && \
    yum install -y epel-release && \
    yum update -y && \
    yum install -y gcc libpcap-devel \
        pcre-devel libyaml-devel \
        file-devel zlib-devel \
        jansson-devel nss-devel \
        libcap-ng-devel libnet-devel \ 
        libnetfilter_queue-devel lua-devel \
        wget tar make && \
    wget https://www.openinfosecfoundation.org/download/suricata-4.1.2.tar.gz && \
    tar -xvzf suricata-4.1.2.tar.gz && \
    cd ./suricata-4.1.2/ && \
    ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-nfqueue --enable-lua && \
    make && make install-full && ldconfig
# Copy the suricata config to its config location
ADD suricata.yaml /etc/suricata/suricata.yaml

# Install Suricata-update utility https://github.com/OISF/suricata-update 
RUN yum install -y python-pip python-yaml && \
    pip install --pre --upgrade suricata-update && \
    yum install -y cronie 
COPY suricata-update.sh /etc/suricata/suricata-update.sh 

# 
RUN yum install -y cronie 
COPY suricata-update-cron /etc/cron.d/suricata-update-cron 
RUN chmod +x /etc/cron.d/suricata-update-cron 
COPY docker-entrypoint.sh ./docker-entrypoint.sh 
RUN chmod +x ./docker-entrypoint.sh 

# eth0 is hardcoded in suricata (recognized as a bug)
RUN grep -rl eth0 /etc | xargs sed -i 's/eth0/ens3/g'

