{
 "title": "Manufacturing Edge Analytics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Produced Parts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Parts" }
   ],
   "targets": [
    { "expr": "em63_actcntprt" }
   ]
  },
  {
   "title": "Machine Sensor Data",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "em63_actsimpara2" }
   ]
  },
  {
   "title": "Cycle Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Time " }
   ],
   "targets": [
    { "expr": "em63_acttimcyc" }
   ]
  }
 ]
}