# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smpccs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smpccs.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0csmpccs.proto\"\x16\n\x07TestMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1f\n\x0f\x46smRegistration\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\tFsmAction\x12\x0c\n\x04type\x18\x01 \x01(\t2c\n\rSmpFsmControl\x12\"\n\nHelloWorld\x12\x08.TestMsg\x1a\x08.TestMsg\"\x00\x12.\n\nControlFsm\x12\x10.FsmRegistration\x1a\n.FsmAction\"\x00\x30\x01\x62\x06proto3')
)




_TESTMSG = _descriptor.Descriptor(
  name='TestMsg',
  full_name='TestMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='TestMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=38,
)


_FSMREGISTRATION = _descriptor.Descriptor(
  name='FsmRegistration',
  full_name='FsmRegistration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FsmRegistration.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=71,
)


_FSMACTION = _descriptor.Descriptor(
  name='FsmAction',
  full_name='FsmAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='FsmAction.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['TestMsg'] = _TESTMSG
DESCRIPTOR.message_types_by_name['FsmRegistration'] = _FSMREGISTRATION
DESCRIPTOR.message_types_by_name['FsmAction'] = _FSMACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestMsg = _reflection.GeneratedProtocolMessageType('TestMsg', (_message.Message,), {
  'DESCRIPTOR' : _TESTMSG,
  '__module__' : 'smpccs_pb2'
  # @@protoc_insertion_point(class_scope:TestMsg)
  })
_sym_db.RegisterMessage(TestMsg)

FsmRegistration = _reflection.GeneratedProtocolMessageType('FsmRegistration', (_message.Message,), {
  'DESCRIPTOR' : _FSMREGISTRATION,
  '__module__' : 'smpccs_pb2'
  # @@protoc_insertion_point(class_scope:FsmRegistration)
  })
_sym_db.RegisterMessage(FsmRegistration)

FsmAction = _reflection.GeneratedProtocolMessageType('FsmAction', (_message.Message,), {
  'DESCRIPTOR' : _FSMACTION,
  '__module__' : 'smpccs_pb2'
  # @@protoc_insertion_point(class_scope:FsmAction)
  })
_sym_db.RegisterMessage(FsmAction)



_SMPFSMCONTROL = _descriptor.ServiceDescriptor(
  name='SmpFsmControl',
  full_name='SmpFsmControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=100,
  serialized_end=199,
  methods=[
  _descriptor.MethodDescriptor(
    name='HelloWorld',
    full_name='SmpFsmControl.HelloWorld',
    index=0,
    containing_service=None,
    input_type=_TESTMSG,
    output_type=_TESTMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ControlFsm',
    full_name='SmpFsmControl.ControlFsm',
    index=1,
    containing_service=None,
    input_type=_FSMREGISTRATION,
    output_type=_FSMACTION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMPFSMCONTROL)

DESCRIPTOR.services_by_name['SmpFsmControl'] = _SMPFSMCONTROL

# @@protoc_insertion_point(module_scope)
